baseURL = "http://example.org/"
languageCode = "en-us"
title = "Standout"
themesDir = "../../"
theme = "hugo-standout"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "About"
url     = "about"
weight  = 2
[[menu.main]]
name    = "Board"
url     = "board"
weight  = 3
[[menu.main]]
name    = "Gallery"
url     = "gallery"
weight  = 4
[[menu.main]]
name    = "FAQ"
url     = "faq"
weight  = 5
[[menu.main]]
name    = "Blog"
url     = "posts"
weight  = 6


# Site Params
[params]
home = "Home"
date_formata = "January 1, 2006"

# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
homeAboutEnable  = true
homeTeamEnable  = true

# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/nikola-majksner-hXNGeAFOgT4-unsplash.jpg"
heading = "Welcome to our website"
description = "OUR 10 YEARS OF COMMUNITY, Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium.."

[params.team]
title = "Meet the team"
homeTeamEnable = true

# Call to Action
[params.cta]
enable  = true
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"